# Generated by Django 6.0.5 on 2026-06-09 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskreminder',
            unique_together=set(),
        ),
    ]
