web: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2
release: python manage.py migrate --settings=config.settings_prod && python manage.py collectstatic --noinput --settings=config.settings_prod
