# Generated by Django 6.0.5 on 2026-06-17 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_forumpost_delete_projectmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='project',
            field=models.ForeignKey(blank=True, help_text='NULL = global forum; set = project-scoped forum', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to='projects.project'),
        ),
    ]
