# Generated by Django 6.0.5 on 2026-06-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_forumpost_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_view',
            field=models.CharField(choices=[('list', 'List'), ('kanban', 'Kanban'), ('calendar', 'Calendar')], default='list', max_length=10),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='notifications_muted',
            field=models.BooleanField(default=False),
        ),
    ]
